### PR TITLE
consolidate auth routes

### PR DESCRIPTION
**Pull request by tobisupreme**
This PR...

## Changes

-

## Fixes
-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [x] updated the Swagger API docs
- [x] updated the Postman collection
- [x] added a test
- [x] linter passes
- [x] format check passes

Fixes #

### CODE REVIEW

**Comment by tobisupreme** [comment]
WiP

**Comment by Boye95** [comment]
Okay. I will get to that now. Thanks

**Comment by Boye95** [comment]
> PR is now ready for review!
> 
> The `/mentors/` and `/students` routes will be consolidated in another PR 🙏
> 
> @Boye95 the "old" routes are still in the app so the downtime is gracious.
> 
> After merging this, let us know when you have finished migrating the `auth` routes so we can remove the old one.

Thanks. I will get to that.

**Review by Boye95 — APPROVED** [review]

**Review by misspee007 — APPROVED** [review]
Looks good.

**Pull request merged**
